version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: iotdb
      MYSQL_USER: iotuser
      MYSQL_PASSWORD: iotpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
  producer:
    build: .
    depends_on:
      - kafka
      - db
    command: ["python", "producer.py"]
    volumes:
      - .:/app
  consumer:
    build: .
    depends_on:
      - kafka
      - db
    command: ["python", "consumer.py"]
    volumes:
      - .:/app
