version: "3.8"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYSPARK_PYTHON=python3
    ports:
      - "8888:8888"
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]

  script:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYSPARK_PYTHON=python3
    command: ["python", "-m", "code_elevate_app.main", "info_transportes.csv"]
