version: "3.8"
services:
  assignment-1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYSPARK_PYTHON=python3
    # Uncomment if you want to keep the container running for debugging
    # tty: true
